version: "3.1"
services:

    node:
      restart: always
      image: node:alpine
      container_name: siep-api-gw
      volumes:
         - "./app:/src/app"
      command: sh -c "cd /src/app && npm install && npm start"
      ports:
         - "7777:80"
      networks:
        - siep-lan

networks:
  siep-lan:
    driver: bridge
